language: android
dist: trusty

android:
  components:
     - platform-tools
     - tools
     - build-tools-26.0.2
     - android-29
     # Additional components
     - extra-google-google_play_services
     - extra-google-m2repository
     - extra-android-m2repository

script: ./gradlew clean build connectedCheck
